pretrained_base_model_path: "./pretrained_weights/sd-image-variations-diffusers"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/sd-image-variations-diffusers/image_encoder"

denoising_unet_path: './pretrained_weights/denoising_unet.pth'
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_encoder_path: "./pretrained_weights/pose_encoder.pth"
motion_module_path: './pretrained_weights/motion_module.pth'

audio_mapper_path: "./pretrained_weights/audio_mapper-50000.pth"
auido_guider_path: "./pretrained_weights/wav2vec2-base-960h"
auto_flow_path: "./pretrained_weights/AutoFlow"
audio_model_path: "./pretrained_weights/audio_processor/whisper_tiny.pt"
inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'
